###  create users
POST http://localhost:8080/users/
Content-Type: application/json

{
  "username": "mgckaled01",
  "name": "Marcel Kaled",
  "password": "654321"
}

### create tasks
POST http://localhost:8080/tasks/
Content-Type: application/json
Authorization: Basic mgckaled01:654321

{
  "title":"Gravação de aula",
  "description": "Tarefa para gravar aula de Tasks do Curso de spring boot",
  "priority": "ALTA",
  "startAt": "2024-10-06T12:30:00",
  "endAt": "2024-10-10T12:30:00"
}

### list tasks
GET http://localhost:8080/tasks/
